//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLibDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        public Nullable<int> BookId { get; set; }
        public string Category { get; set; }
        public int id { get; set; }
    
        public virtual books books { get; set; }
    }
}
