//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLibDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class copies
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual books books { get; set; }
        public virtual users users { get; set; }
    }
}
